name: BukkitRichPresenceExamples
version: ${project.version}
main: net.trollyloki.bukkit_rich_presence.examples.BukkitRichPresenceExamplesPlugin
api-version: 1.16
author: TrollyLoki

commands:
  test-presence: